const X = 0
const Y = 1
const CHUNK_SIZE = 20 * 20
const CHUNK_FILE_RATIO = 5
const BUTTONS_PER_BYTE = 4
const CHUNK_SIZE_BYTES = CHUNK_SIZE / BUTTONS_PER_BYTE
const FILE_SIZE = 100 * 100 / BUTTONS_PER_BYTE
const MAX_CACHE_SIZE = 10000

module.exports = {
	X, Y, CHUNK_SIZE, CHUNK_FILE_RATIO, BUTTONS_PER_BYTE, CHUNK_SIZE_BYTES, FILE_SIZE, MAX_CACHE_SIZE
}
